import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "./theme-provider";
import { ThemeSwitcher } from "@/components/ThemeSwitcher";
import { Space_Grotesk } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });
const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Ye Htet Portfolio",
  description: "Generated by ye htet aung",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
  
      <body className={`${inter.className} ${spaceGrotesk.className}`} >
        <ThemeProvider  attribute="class" defaultTheme="system" enableSystem>
        <Navbar />
        <ThemeSwitcher />
        {children}
        </ThemeProvider>

        </body>
       
    </html>
  );
}
